"""Compatibility facade for legacy arena transaction services."""

from ...compatibility.legacy_arena_transactions import (
    ARENA_FIELDS,
    ArenaStateService,
    ArenaPurchaseResult,
    ArenaPurchaseService,
    ArenaChallengePurchaseResult,
    ArenaChallengePurchaseService,
    ArenaChallengeTicketResult,
    ArenaChallengeSettlementResult,
    ArenaChallengeSettlementService,
    ArenaBattleSettlementResult,
    ArenaBattleSettlementService,
    ArenaWeeklyRankReductionResult,
    ArenaWeeklyRankReductionService,
    ArenaSeasonRewardResult,
    ArenaSeasonRewardService,
    normalize_weekly_purchases,
    normalize_daily_purchase_state,
)

__all__ = [
    "ArenaStateService",
    "ArenaPurchaseResult",
    "ArenaPurchaseService",
    "ArenaChallengePurchaseResult",
    "ArenaChallengePurchaseService",
    "ArenaChallengeTicketResult",
    "ArenaChallengeSettlementResult",
    "ArenaChallengeSettlementService",
    "ArenaBattleSettlementResult",
    "ArenaBattleSettlementService",
    "ArenaWeeklyRankReductionResult",
    "ArenaWeeklyRankReductionService",
    "ArenaSeasonRewardResult",
    "ArenaSeasonRewardService",
    "ARENA_FIELDS",
    "normalize_weekly_purchases",
    "normalize_daily_purchase_state",
]
