from __future__ import annotations

import unittest

from scripts.check_full_refactor_progress import _slice_status


class RefactorProgressTests(unittest.TestCase):
    def test_progress_report_tracks_interactive_command_ownership(self) -> None:
        interactive = _slice_status()["interactive"]
        self.assertTrue(interactive["static_commands_remain_message_only"])
        self.assertTrue(interactive["effectful_commands_use_interactive_application"])
        self.assertTrue(interactive["application_and_repository_own_reward_effects"])
        self.assertTrue(interactive["startup_migration_manifest_and_service_registered"])
        self.assertTrue(interactive["exp_application_replay_and_asset_effect_tested"])
        self.assertTrue(interactive["legacy_fortune_suppression_has_migrated_matcher"])

    def test_progress_report_tracks_bounded_unique_nearby_display(self) -> None:
        mapping = _slice_status()["map"]
        self.assertTrue(mapping["nearby_display_feature_owned"])
        self.assertTrue(mapping["nearby_display_unique_uid_seek_and_first_pair"])
        self.assertTrue(mapping["nearby_display_bounded_short_read_only"])
        self.assertTrue(mapping["nearby_display_fair_sample_and_legacy_small_order"])
        self.assertTrue(mapping["nearby_display_full_list_and_unbounded_seen_disabled"])

    def test_progress_report_tracks_bounded_fair_random_map_target(self) -> None:
        mapping = _slice_status()["map"]
        self.assertTrue(mapping["random_nearby_target_feature_owned"])
        self.assertTrue(mapping["random_nearby_target_bounded_short_read_only"])
        self.assertTrue(mapping["random_nearby_target_pair_weight_and_boundaries_preserved"])
        self.assertTrue(mapping["random_nearby_target_fair_cooperative_fail_closed"])
        self.assertTrue(mapping["random_nearby_target_full_list_disabled"])

    def test_progress_report_tracks_single_named_map_target(self) -> None:
        mapping = _slice_status()["map"]
        self.assertTrue(mapping["named_nearby_target_feature_owned"])
        self.assertTrue(mapping["named_nearby_target_single_row_read_only"])
        self.assertTrue(mapping["named_nearby_self_and_empty_semantics_preserved"])
        self.assertTrue(mapping["named_nearby_full_list_disabled"])

    def test_progress_report_tracks_bounded_random_dongfu_selection(self) -> None:
        dongfu = _slice_status()["dongfu"]
        self.assertTrue(dongfu["random_target_feature_owned"])
        self.assertTrue(dongfu["random_target_bounded_short_read_only"])
        self.assertTrue(dongfu["random_target_fair_cooperative_fail_closed"])
        self.assertTrue(dongfu["legacy_random_target_full_list_disabled"])

    def test_progress_report_tracks_single_named_dongfu_target(self) -> None:
        dongfu = _slice_status()["dongfu"]
        self.assertTrue(dongfu["named_target_feature_owned"])
        self.assertTrue(dongfu["named_target_single_row_read_only"])
        self.assertTrue(dongfu["legacy_named_target_list_disabled"])

    def test_progress_report_separates_retained_cache_from_query_peak(self) -> None:
        cache = _slice_status()["field_list_cache"]
        self.assertTrue(cache["shared_entry_and_byte_budget"])
        self.assertTrue(cache["bounded_charge_before_and_after_copy"])
        self.assertTrue(cache["expiry_invalidation_and_lifecycle_release"])
        self.assertEqual(cache["status"], "retained_cache_bounded_query_materialization_open")

    def test_progress_report_tracks_daily_beg_reset_ownership(self) -> None:
        beg = _slice_status()["beg"]
        self.assertTrue(beg["daily_reset_application_owned"])
        self.assertTrue(beg["daily_reset_atomic_no_request_ddl"])
        self.assertTrue(beg["daily_reset_replay_rollback_and_missing_schema_covered"])

    def test_progress_report_tracks_replay_safe_map_and_pet_claim_effects(self) -> None:
        claims = _slice_status()["game_event_claims"]
        self.assertTrue(claims["pet_travel_claim_effects_outbox_owned"])
        self.assertTrue(claims["pet_travel_claim_effects_dispatched_on_replay"])
        self.assertTrue(claims["claim_projection_receipts_and_migrations_owned"])
        self.assertTrue(claims["claim_projection_runtime_and_cli_reconcile_owned"])
        self.assertTrue(claims["claim_operation_recovery_runtime_and_cli_owned"])
        self.assertTrue(claims["claim_projection_migrations_routed"])
        map_status = _slice_status()["map"]
        self.assertTrue(map_status["mission_claim_effects_outbox_owned"])
        self.assertTrue(map_status["mission_claim_effects_dispatched_on_replay"])

    def test_progress_report_separates_direct_breakthrough_core_from_effect_recovery(self) -> None:
        base = _slice_status()["base"]
        self.assertTrue(base["direct_breakthrough_handler_feature_owned"])
        self.assertTrue(base["direct_breakthrough_startup_migration_registered"])
        self.assertTrue(base["direct_breakthrough_request_path_has_no_ddl"])
        self.assertTrue(base["direct_breakthrough_effects_replay_owned"])
        self.assertTrue(base["direct_breakthrough_effects_runtime_and_cli_owned"])
        self.assertTrue(base["direct_breakthrough_effects_migrations_routed"])

    def test_progress_report_tracks_recoverable_closing_effects(self) -> None:
        buff = _slice_status()["buff"]
        self.assertTrue(buff["closing_settlement_replay_application_owned"])
        self.assertTrue(buff["closing_settlement_request_path_has_no_ddl"])
        self.assertTrue(buff["closing_effects_runtime_and_cli_reconcile_owned"])
        self.assertTrue(buff["closing_effect_projections_have_stable_receipts"])
        self.assertTrue(buff["closing_effects_migrations_routed"])

    def test_progress_report_tracks_avatar_identity_cutover(self) -> None:
        avatar = _slice_status()["avatar_identity"]
        self.assertTrue(avatar["migration_is_player_db_only"])
        self.assertTrue(avatar["initialization_migration_is_player_db_only"])
        self.assertTrue(avatar["legacy_avatar_rows_preserved_and_prebuilt"])
        self.assertTrue(avatar["active_id_writes_are_player_owned_and_atomic"])
        self.assertTrue(avatar["active_id_reads_use_application_and_preserve_priority"])
        self.assertTrue(avatar["initialization_is_player_application_owned_and_recoverable"])
        self.assertTrue(avatar["request_path_has_no_ddl"])

    def test_progress_report_tracks_dufang_share_repository_cutover(self) -> None:
        dufang = _slice_status()["dufang"]
        self.assertTrue(dufang["share_application_owned"])
        self.assertTrue(dufang["share_resume_reachable"])
        self.assertTrue(dufang["share_repository_owned"])
        self.assertTrue(dufang["share_legacy_settlement_disabled"])
        self.assertTrue(dufang["share_request_path_has_no_ddl"])
        self.assertTrue(dufang["share_ledger_identity_stable"])
        self.assertTrue(dufang["share_player_receipt_recovery_owned"])
        self.assertTrue(dufang["share_migrations_registered_and_routed"])
        self.assertTrue(dufang["bet_payout_request_path_has_no_ddl"])
        self.assertTrue(dufang["bet_payout_missing_schema_fails_closed"])
        self.assertTrue(dufang["bet_payout_migration_registered"])
        self.assertTrue(dufang["bet_resolution_migrations_registered"])
        self.assertTrue(dufang["bet_resolution_replay_uses_frozen_plan"])
        self.assertTrue(dufang["bet_payout_player_stats_use_outbox_receipts"])
        self.assertTrue(dufang["bet_payout_started_ledger_recovers"])
        self.assertTrue(dufang["bet_payout_pending_reconciliation_is_bounded"])
        self.assertTrue(dufang["storage_audit_is_read_only_and_bounded"])
        self.assertTrue(dufang["backup_capacity_preflight_is_shared_and_fail_closed"])
        self.assertTrue(dufang["payout_result_is_read_only"])

    def test_progress_report_tracks_compensation_claim_cleanup_boundary(self) -> None:
        compensation = _slice_status()["compensation"]
        self.assertTrue(compensation["claim_delete_application_owned"])
        self.assertTrue(compensation["claim_delete_request_path_has_no_ddl"])
        self.assertTrue(compensation["claim_delete_is_atomic_with_definition"])
        self.assertTrue(compensation["claim_delete_admin_handlers_handle_failure"])

    def test_progress_report_tracks_boss_weekly_purchase_read_ownership(self) -> None:
        boss = _slice_status()["boss"]
        self.assertTrue(boss["weekly_purchase_snapshot_application_owned"])
        self.assertTrue(boss["weekly_purchase_snapshot_read_only_and_no_ddl"])
        self.assertTrue(boss["weekly_purchase_handlers_use_feature_snapshot"])
        self.assertTrue(boss["weekly_purchase_snapshot_and_write_share_schema_selection"])
        self.assertTrue(boss["weekly_purchase_legacy_row_initialized_only_on_success"])

    def test_progress_report_tracks_arena_cutovers_and_active_blockers(self) -> None:
        slices = _slice_status()
        arena = slices["arena"]
        self.assertTrue(arena["state_application_owned"])
        self.assertTrue(arena["legacy_state_owner_disabled"])
        self.assertTrue(arena["legacy_transaction_service_isolated"])
        self.assertTrue(arena["legacy_transaction_imports_explicit"])
        self.assertTrue(arena["weekly_rank_application_owned"])
        self.assertTrue(arena["legacy_scheduler_disabled"])
        self.assertTrue(arena["daily_reward_application_owned"])
        self.assertTrue(arena["legacy_daily_reward_disabled"])
        self.assertFalse(slices["sign_in"]["lottery_compatibility_fallback"])
        self.assertTrue(slices["sign_in"]["effects_outbox_reconcile_owned"])
        tasks = slices["tasks"]
        self.assertTrue(tasks["progress_application_owned"])
        self.assertTrue(tasks["progress_repository_owned"])
        self.assertTrue(tasks["progress_request_path_has_no_ddl"])
        self.assertTrue(tasks["progress_migration_registered"])
        self.assertTrue(tasks["claim_schema_migration_registered"])
        self.assertTrue(tasks["claim_recovery_migrations_registered"])
        self.assertTrue(tasks["claim_application_owned"])
        self.assertTrue(tasks["claim_default_entry_owned"])
        self.assertTrue(tasks["claim_task_definition_compatibility"])
        self.assertTrue(tasks["claim_started_operation_recoverable"])
        self.assertTrue(tasks["claim_request_path_has_no_ddl"])
        self.assertTrue(tasks["claim_request_path_avoids_attached_transaction"])
        self.assertTrue(tasks["claim_schema_migrations_owned"])
        self.assertTrue(tasks["reward_claim_legacy_boundary"])
        self.assertTrue(tasks["legacy_progress_implementation_retained"])
        self.assertTrue(tasks["legacy_transaction_reexports_explicit"])
        tower = slices["tower"]
        self.assertTrue(tower["state_application_owned"])
        self.assertTrue(tower["legacy_state_owner_disabled"])
        self.assertTrue(tower["global_reset_application_owned"])
        self.assertTrue(tower["global_reset_repository_atomic"])
        self.assertTrue(tower["global_reset_request_path_has_no_ddl"])
        self.assertTrue(tower["global_reset_replay_protected"])
        self.assertTrue(tower["global_reset_schema_migration_owned"])
        self.assertTrue(tower["global_reset_scheduler_uses_stable_week_id"])
        self.assertTrue(tower["global_reset_admin_uses_event_id"])
        self.assertTrue(tower["ranking_application_owned"])
        self.assertTrue(tower["ranking_query_bounded_and_stable"])
        self.assertTrue(tower["ranking_legacy_full_scan_removed"])
        training = slices["training"]
        self.assertTrue(training["state_application_owned"])
        self.assertTrue(training["legacy_state_owner_disabled"])
        self.assertTrue(training["event_application_owned"])
        self.assertTrue(training["event_default_entry_owned"])
        self.assertTrue(training["event_repository_atomic"])
        self.assertTrue(training["event_request_path_has_no_ddl"])
        self.assertTrue(training["event_migrations_registered"])
        self.assertTrue(training["purchase_application_owned"])
        self.assertTrue(training["purchase_default_entry_owned"])
        self.assertTrue(training["purchase_repository_atomic"])
        self.assertTrue(training["purchase_request_path_has_no_ddl"])
        self.assertTrue(training["purchase_migrations_registered"])
        self.assertTrue(training["reset_application_owned"])
        self.assertTrue(training["reset_default_entry_owned"])
        self.assertTrue(training["reset_repository_atomic"])
        self.assertTrue(training["reset_request_path_has_no_ddl"])
        self.assertTrue(training["reset_clock_injected"])
        self.assertTrue(training["reset_migrations_registered"])
        self.assertTrue(training["item_catalog_is_lazy_and_shared"])
        self.assertTrue(training["purchase_reset_compatibility_retained"])
        work = slices["work"]
        self.assertTrue(work["daily_refresh_application_owned"])
        self.assertTrue(work["legacy_daily_refresh_disabled"])
        self.assertTrue(work["admin_global_reset_application_owned"])
        self.assertTrue(work["admin_global_reset_reuses_platform_ledger"])
        self.assertTrue(work["admin_global_reset_atomic_without_ddl_or_user_cache"])
        self.assertTrue(work["admin_global_reset_replay_conflict_and_rollback_covered"])
        self.assertTrue(work["item_accelerate_application_owned"])
        self.assertTrue(work["legacy_item_accelerate_disabled"])
        self.assertTrue(work["capture_application_owned"])
        self.assertTrue(work["legacy_item_capture_disabled"])
        self.assertTrue(work["capture_json_projection_only"])
        self.assertTrue(work["offer_generation_reuses_profile_snapshot"])
        self.assertTrue(work["offer_generation_has_no_legacy_handle_import"])
        self.assertTrue(work["unused_item_cache_not_constructed"])
        self.assertTrue(work["refresh_application_owned"])
        self.assertTrue(work["legacy_refresh_default_path_disabled"])
        self.assertTrue(work["refresh_repository_has_no_request_ddl"])
        self.assertTrue(work["offer_projection_has_no_request_ddl"])
        self.assertTrue(work["refresh_migration_registered"])
        self.assertTrue(work["legacy_refresh_isolated_with_compatibility_export"])
        self.assertTrue(work["abort_cleanup_application_owned"])
        self.assertTrue(work["legacy_abort_cleanup_default_path_disabled"])
        self.assertTrue(work["abort_cleanup_repository_has_no_request_ddl"])
        self.assertTrue(work["abort_cleanup_migration_registered"])
        self.assertTrue(work["legacy_abort_cleanup_isolated_with_compatibility_export"])
        self.assertTrue(work["claim_default_entry_owned"])
        self.assertTrue(work["claim_runtime_default_has_no_legacy_repository"])
        self.assertTrue(work["claim_repository_has_no_request_ddl"])
        self.assertTrue(work["claim_migration_registered"])
        self.assertTrue(work["settlement_repository_has_no_request_ddl"])
        self.assertTrue(work["settlement_migration_registered"])
        self.assertTrue(work["settlement_application_owned"])
        self.assertTrue(work["settlement_transaction_owned"])
        self.assertTrue(work["legacy_settlement_isolated_with_compatibility_export"])
        self.assertTrue(work["legacy_item_use_isolated_with_compatibility_export"])
        self.assertTrue(work["legacy_daily_refresh_isolated_with_compatibility_export"])
        self.assertTrue(work["item_use_migrations_registered"])
        activity = slices["activity_reward"]
        self.assertTrue(activity["claim_all_application_owned"])
        self.assertTrue(activity["legacy_claim_all_disabled"])
        self.assertTrue(activity["claim_all_startup_schema_owned"])
        self.assertTrue(activity["claim_all_legacy_receipts_imported"])
        self.assertTrue(activity["claim_all_game_db_default"])
        self.assertTrue(activity["claim_all_web_default_owned"])
        self.assertTrue(activity["claim_all_command_default_owned"])
        self.assertTrue(activity["tasks_game_reward_application_owned"])
        self.assertTrue(activity["tasks_started_operation_recoverable"])
        self.assertTrue(activity["tasks_startup_schema_and_receipt_backfill"])
        self.assertTrue(activity["tasks_legacy_state_projection_retryable"])
        self.assertTrue(activity["task_claim_matcher_operation_id_owned"])
        self.assertTrue(activity["pass_game_reward_application_owned"])
        self.assertTrue(activity["pass_started_operation_recoverable"])
        self.assertTrue(activity["pass_startup_schema_and_receipt_backfill"])
        self.assertTrue(activity["pass_legacy_state_projection_retryable"])
        self.assertTrue(activity["pass_claim_matcher_operation_id_owned"])
        self.assertTrue(activity["pass_compatibility_facade_isolated"])
        self.assertTrue(activity["pass_claim_all_child_operation_id_stable"])
        self.assertTrue(activity["boss_milestone_game_reward_application_owned"])
        self.assertTrue(activity["boss_milestone_started_operation_recoverable"])
        self.assertTrue(activity["boss_milestone_startup_schema_and_receipt_backfill"])
        self.assertTrue(activity["boss_milestone_legacy_state_projection_retryable"])
        self.assertTrue(activity["boss_milestone_compatibility_facade_isolated"])
        self.assertTrue(activity["boss_milestone_claim_all_child_operation_id_stable"])
        self.assertTrue(activity["boss_claim_matcher_operation_id_owned"])
        self.assertTrue(activity["boss_rank_game_reward_application_owned"])
        self.assertTrue(activity["boss_rank_started_operation_recoverable"])
        self.assertTrue(activity["boss_rank_startup_schema_and_receipt_backfill"])
        self.assertTrue(activity["boss_rank_legacy_state_projection_retryable"])
        self.assertTrue(activity["boss_rank_compatibility_facade_isolated"])
        self.assertTrue(activity["boss_rank_claim_all_child_operation_id_stable"])
        self.assertTrue(activity["state_migrations_registered_game_only"])
        self.assertTrue(activity["state_legacy_backfill_read_only_bounded_conflict_checked"])
        self.assertTrue(activity["state_migration_disk_preflight"])
        self.assertTrue(activity["state_default_storage_is_game_db"])
        self.assertTrue(activity["state_transaction_services_use_migrated_schema"])
        self.assertTrue(activity["state_default_reward_and_boss_paths_use_game_db"])
        self.assertTrue(activity["state_web_management_targets_game_db_and_keeps_config_separate"])
        self.assertTrue(activity["state_legacy_projection_cutover_complete_but_source_retained"])
        read_model = slices["activity_read_model"]
        self.assertTrue(read_model["task_and_pass_matchers_use_feature_application"])
        self.assertTrue(read_model["activity_application_composes_read_model"])
        self.assertTrue(read_model["read_model_repository_is_read_only_and_has_no_ddl"])
        self.assertTrue(read_model["read_model_rendering_matches_legacy_contract"])
        config_owner = slices["activity_config_owner"]
        self.assertTrue(config_owner["activity_overview_reward_gameplay_matchers_use_feature_read_model"])
        self.assertTrue(config_owner["activity_overview_uses_one_read_only_game_snapshot"])
        self.assertTrue(config_owner["config_toggle_matchers_use_separate_config_application"])
        self.assertTrue(config_owner["config_owner_uses_activity_event_store_and_repairs_projection_replay"])
        self.assertTrue(config_owner["config_owner_target_replay_conflict_and_revision_contracts_tested"])
        activity_web_config = slices["activity_web_config_owner"]
        self.assertTrue(activity_web_config["management_and_config_routes_use_feature_config_application"])
        self.assertTrue(activity_web_config["configuration_http_contracts_are_exercised_through_flask_client"])
        self.assertTrue(activity_web_config["static_template_routes_are_explicit_read_only_compatibility"])
        activity_web_admin_data = slices["activity_web_admin_data_owner"]
        self.assertTrue(activity_web_admin_data["data_routes_use_feature_owned_admin_data_application"])
        self.assertTrue(activity_web_admin_data["admin_data_uses_read_only_snapshot_and_atomic_existing_schema_writes"])
        self.assertTrue(activity_web_admin_data["admin_data_http_and_legacy_response_contracts_are_tested"])
        web_pages = slices["web_pages_presentation_owner"]
        self.assertTrue(web_pages["page_handlers_remain_session_template_or_static_adapters"])
        self.assertTrue(web_pages["page_permissions_and_global_csrf_remain_declared"])
        self.assertTrue(web_pages["browser_session_and_static_http_contracts_are_tested"])
        updater = slices["updater_owner"]
        self.assertTrue(updater["status_commands_use_updater_application"])
        self.assertTrue(updater["web_update_routes_use_updater_application"])
        self.assertTrue(updater["application_preflights_asset_and_orders_backups_before_update"])
        self.assertTrue(updater["remote_release_metadata_is_rendered_as_text"])
        self.assertTrue(updater["updater_application_manager_and_http_contracts_are_tested"])
        backup_catalog = slices["plugin_backup_catalog_owner"]
        self.assertTrue(backup_catalog["legacy_route_uses_catalog_application"])
        self.assertTrue(backup_catalog["catalog_preserves_list_contract_without_path_disclosure"])
        self.assertTrue(backup_catalog["catalog_is_read_only_and_handles_missing_entries"])
        self.assertTrue(backup_catalog["catalog_application_and_http_contracts_are_tested"])
        backup_files = slices["plugin_backup_local_file_owner"]
        self.assertTrue(backup_files["legacy_file_routes_use_feature_application"])
        self.assertTrue(backup_files["file_operations_share_catalog_filename_policy_and_reject_symlinks"])
        self.assertTrue(backup_files["batch_delete_preserves_partial_result_contract"])
        self.assertTrue(backup_files["file_repository_and_http_contracts_are_tested"])
        backup_restore = slices["plugin_backup_restore_owner"]
        self.assertTrue(backup_restore["both_legacy_restore_routes_share_feature_application"])
        self.assertTrue(backup_restore["application_owns_restore_order_and_runtime_boundary"])
        self.assertTrue(backup_restore["repository_bounds_and_validates_zip_before_overlay"])
        self.assertTrue(backup_restore["restore_behavior_and_failure_boundaries_are_tested"])
        backup_cloud = slices["plugin_backup_cloud_owner"]
        self.assertTrue(backup_cloud["legacy_cloud_routes_use_feature_application"])
        self.assertTrue(backup_cloud["cloud_restore_fetch_and_restore_share_feature_owners"])
        self.assertTrue(backup_cloud["application_bounds_batches_and_preserves_partial_results"])
        self.assertTrue(backup_cloud["repository_bounds_webdav_and_atomically_installs_archives"])
        self.assertTrue(backup_cloud["manager_compatibility_methods_and_cloud_contracts_are_tested"])
        activity_static_help = slices["activity_static_help"]
        self.assertTrue(activity_static_help["help_and_manage_remain_static_compatibility_handlers"])
        boss = slices["activity_boss"]
        self.assertTrue(boss["boss_status_matcher_uses_feature_read_model"])
        self.assertTrue(boss["boss_rank_matcher_uses_feature_read_model"])
        self.assertTrue(boss["boss_read_repository_is_read_only_bounded_no_hp_init"])
        self.assertTrue(boss["boss_attack_application_owned"])
        self.assertTrue(boss["boss_settlement_atomic_replay_conflict_cas_and_rollback"])
        self.assertTrue(boss["boss_settlement_uses_existing_state_schema"])
        self.assertTrue(boss["boss_operation_id_and_item_damage_stable"])
        self.assertTrue(boss["boss_legacy_settlement_default_path_isolated"])
        points_shop = slices["activity_points_shop"]
        self.assertTrue(points_shop["default_read_matchers_use_feature_read_model"])
        self.assertTrue(points_shop["default_purchase_uses_feature_owned_repository"])
        self.assertTrue(points_shop["purchase_assets_and_receipt_share_atomic_startup_schema"])
        self.assertTrue(points_shop["historical_receipts_replay_without_started_retry"])
        dungeon_team = slices["dungeon_team"]
        self.assertTrue(dungeon_team["team_commands_application_owned"])
        self.assertTrue(dungeon_team["legacy_team_service_factories_removed"])
        self.assertTrue(dungeon_team["team_reads_application_owned"])
        self.assertTrue(dungeon_team["legacy_team_read_helpers_disabled"])
        self.assertTrue(dungeon_team["invite_expiry_application_owned"])
        self.assertTrue(dungeon_team["invite_mapping_isolated"])
        self.assertTrue(dungeon_team["legacy_team_transaction_service_isolated"])
        self.assertTrue(dungeon_team["legacy_team_transaction_imports_explicit"])
        self.assertTrue(dungeon_team["team_presentation_feature_owned"])
        self.assertTrue(dungeon_team["team_presentation_legacy_identity_preserved"])
        self.assertTrue(dungeon_team["team_schema_startup_migrated"])
        self.assertTrue(dungeon_team["team_members_projection_migrated"])
        self.assertTrue(dungeon_team["team_member_lookup_bounded"])
        self.assertTrue(dungeon_team["explore_team_lookup_bounded"])
        self.assertTrue(dungeon_team["team_user_lookup_game_owner"])
        self.assertTrue(dungeon_team["team_membership_projection_sync"])
        self.assertTrue(dungeon_team["team_reads_use_read_only_uow"])
        self.assertTrue(dungeon_team["team_request_path_has_no_ddl"])
        self.assertTrue(dungeon_team["team_schema_missing_fails_closed"])
        self.assertTrue(dungeon_team["session_schema_missing_fails_closed"])
        self.assertTrue(dungeon_team["session_aba_schema_required"])
        self.assertTrue(dungeon_team["explore_settlement_schema_startup_migrated"])
        self.assertTrue(dungeon_team["explore_settlement_request_path_has_no_ddl"])
        self.assertTrue(dungeon_team["explore_settlement_missing_schema_retryable"])
        self.assertTrue(dungeon_team["dungeon_reset_request_path_has_no_ddl"])
        self.assertTrue(dungeon_team["dungeon_global_state_read_feature_owned"])
        self.assertTrue(dungeon_team["reset_clock_injected"])
        self.assertTrue(dungeon_team["reset_business_date_uses_scheduler_timezone"])
        self.assertTrue(dungeon_team["reset_crossday_business_date_frozen"])
        self.assertTrue(dungeon_team["reset_progress_uses_published_snapshot"])
        self.assertTrue(dungeon_team["reset_manual_crossday_replay_covered"])
        self.assertTrue(dungeon_team["explore_random_sources_operation_scoped"])
        self.assertTrue(dungeon_team["explore_resolution_intent_frozen_inputs"])
        bank = slices["bank"]
        self.assertTrue(bank["deposit_application_owned"])
        self.assertTrue(bank["v1_web_game_db_owned"])
        self.assertTrue(bank["v1_web_started_operation_recoverable"])
        self.assertTrue(bank["v1_web_snapshots_checked"])
        self.assertTrue(bank["request_time_legacy_bootstrap_removed"])
        self.assertTrue(bank["withdrawal_application_owned"])
        self.assertTrue(bank["upgrade_application_owned"])
        self.assertTrue(bank["interest_application_owned"])
        self.assertTrue(bank["legacy_deposit_disabled"])
        self.assertTrue(bank["legacy_withdrawal_disabled"])
        self.assertTrue(bank["legacy_upgrade_disabled"])
        self.assertTrue(bank["legacy_interest_disabled"])
        self.assertTrue(bank["legacy_operation_receipts_read_only"])
        self.assertTrue(bank["legacy_account_reads_removed_from_matcher"])
        self.assertTrue(bank["legacy_account_reader_is_explicit_read_only_compatibility"])
        self.assertTrue(bank["legacy_account_write_compatibility_isolated"])
        self.assertTrue(bank["legacy_account_writer_has_no_production_callers"])
        self.assertTrue(bank["legacy_account_reader_has_no_production_callers"])
        self.assertTrue(bank["bank_interest_scheduler_absent"])
        self.assertTrue(bank["legacy_bank_rollback_not_default_composed"])
        self.assertTrue(bank["account_schema_migration_required"])
        self.assertTrue(bank["account_writes_require_startup_schema"])
        self.assertTrue(bank["legacy_account_request_fallbacks_removed"])
        self.assertTrue(bank["legacy_account_backfill_is_bounded_conflict_checked_and_space_preflighted"])
        self.assertTrue(bank["legacy_json_sync_imports_only_missing_game_accounts"])
        self.assertTrue(bank["first_upgrade_and_interest_bootstrap_owned"])
        self.assertTrue(bank["upgrade_preserves_interest_clock"])
        map_slice = slices["map"]
        self.assertTrue(map_slice["interactive_application_owned"])
        self.assertTrue(map_slice["resource_application_owned"])
        self.assertTrue(map_slice["combat_engine_injected"])
        self.assertTrue(map_slice["reward_resolver_feature_owned"])
        self.assertTrue(map_slice["map_item_catalog_lazy"])
        self.assertTrue(map_slice["static_json_provider_owned"])
        self.assertTrue(map_slice["legacy_interactive_disabled"])
        self.assertTrue(map_slice["legacy_resource_disabled"])
        self.assertTrue(map_slice["legacy_transactions_isolated"])
        self.assertTrue(map_slice["legacy_transaction_compatibility_explicit"])
        self.assertTrue(map_slice["map_dtos_feature_owned"])
        sect = slices["sect"]
        self.assertTrue(sect["membership_application_owned"])
        self.assertTrue(sect["membership_service_isolated"])
        self.assertTrue(sect["membership_compatibility_import_isolated"])
        self.assertTrue(sect["economy_application_owned"])
        self.assertTrue(sect["daily_maintenance_application_owned"])
        self.assertTrue(sect["daily_maintenance_service_isolated"])
        self.assertTrue(sect["daily_maintenance_rollback_import_isolated"])
        self.assertTrue(sect["legacy_membership_disabled"])
        self.assertTrue(sect["legacy_membership_getter_removed"])
        self.assertTrue(sect["legacy_transaction_service_import_removed"])
        self.assertTrue(sect["stale_legacy_service_getters_removed"])
        self.assertTrue(sect["owner_inherit_application_owned"])
        self.assertTrue(sect["owner_inherit_service_isolated"])
        self.assertTrue(sect["close_mountain_application_owned"])
        self.assertTrue(sect["close_mountain_service_isolated"])
        self.assertTrue(sect["join_state_application_owned"])
        self.assertTrue(sect["join_state_services_isolated"])
        self.assertTrue(sect["disband_application_owned"])
        self.assertTrue(sect["disband_services_isolated"])
        self.assertTrue(sect["disband_rollback_import_isolated"])
        self.assertTrue(sect["weekly_claim_application_owned"])
        self.assertTrue(sect["weekly_claim_legacy_service_isolated"])
        self.assertTrue(sect["weekly_claim_rollback_import_isolated"])
        self.assertTrue(sect["weekly_status_sect_info_application_owned"])
        self.assertTrue(sect["weekly_claim_repository_owned"])
        self.assertTrue(sect["weekly_claim_request_path_has_no_ddl"])
        self.assertTrue(sect["weekly_claim_migrations_registered"])
        self.assertTrue(sect["weekly_claim_player_migration_routed"])
        self.assertTrue(sect["weekly_claim_default_has_no_legacy_service"])
        self.assertTrue(sect["scheduled_grant_application_owned"])
        self.assertTrue(sect["scheduled_grant_target_query_application_owned"])
        self.assertTrue(sect["scheduled_grant_repository_owned"])
        self.assertTrue(sect["scheduled_grant_request_path_has_no_ddl"])
        self.assertTrue(sect["scheduled_grant_success_result_owned"])
        self.assertTrue(sect["scheduled_grant_migration_registered"])
        self.assertTrue(sect["scheduled_grant_migration_game_only"])
        self.assertTrue(sect["fairyland_claim_status_application_owned"])
        self.assertTrue(sect["fairyland_claim_status_repository_owned"])
        self.assertTrue(sect["fairyland_claim_status_read_only"])
        self.assertTrue(sect["fairyland_claim_status_no_player_manager"])
        self.assertTrue(sect["fairyland_claim_service_isolated"])
        self.assertTrue(sect["fairyland_claim_rollback_import_isolated"])
        self.assertTrue(sect["elixir_claim_application_owned"])
        self.assertTrue(sect["elixir_claim_service_isolated"])
        self.assertTrue(sect["elixir_claim_rollback_import_isolated"])
        self.assertTrue(sect["member_join_service_isolated"])
        self.assertTrue(sect["member_join_rollback_import_isolated"])
        self.assertTrue(sect["shop_purchase_application_owned"])
        self.assertTrue(sect["shop_purchase_service_isolated"])
        self.assertTrue(sect["shop_purchase_rollback_import_isolated"])
        self.assertTrue(sect["main_buff_learn_application_owned"])
        self.assertTrue(sect["main_buff_learn_service_isolated"])
        self.assertTrue(sect["main_buff_learn_rollback_import_isolated"])
        self.assertTrue(sect["secondary_buff_learn_application_owned"])
        self.assertTrue(sect["secondary_buff_learn_service_isolated"])
        self.assertTrue(sect["secondary_buff_learn_rollback_import_isolated"])
        self.assertTrue(sect["sect_default_repository_has_no_legacy_fallback"])
        self.assertTrue(sect["sect_task_claim_application_owned"])
        self.assertTrue(sect["sect_task_claim_repository_owned"])
        self.assertTrue(sect["sect_task_claim_request_path_has_no_ddl"])
        self.assertTrue(sect["sect_task_claim_migration_registered"])
        self.assertTrue(sect["sect_task_claim_migration_game_only"])
        self.assertTrue(sect["task_settlement_repository_owned"])
        self.assertTrue(sect["task_settlement_request_path_has_no_ddl"])
        self.assertTrue(sect["task_settlement_clock_injected"])
        self.assertTrue(sect["task_settlement_migration_registered"])
        self.assertTrue(sect["task_settlement_migration_game_only"])
        self.assertTrue(sect["sect_directory_application_owned"])
        self.assertTrue(sect["sect_directory_repository_owned"])
        self.assertTrue(sect["sect_directory_query_read_only"])
        self.assertTrue(sect["sect_active_names_repository_owned"])
        self.assertTrue(sect["sect_active_names_application_owned"])
        self.assertTrue(sect["sect_info_application_owned"])
        self.assertTrue(sect["sect_info_repository_owned"])
        self.assertTrue(sect["sect_info_repository_read_only"])
        self.assertTrue(sect["sect_id_by_name_repository_owned"])
        self.assertTrue(sect["sect_id_by_name_application_owned"])
        self.assertTrue(sect["inactive_owner_sect_state_application_owned"])
        self.assertTrue(sect["inactive_owner_sect_state_repository_owned"])
        self.assertTrue(sect["inactive_owner_sect_state_read_only"])
        self.assertTrue(sect["inactive_owner_profile_application_owned"])
        self.assertTrue(sect["inactive_owner_profile_repository_owned"])
        self.assertTrue(sect["inactive_owner_reads_fully_feature_owned"])
        self.assertTrue(sect["sect_member_list_application_owned"])
        self.assertTrue(sect["sect_member_list_repository_owned"])
        self.assertTrue(sect["sect_member_list_read_only"])
        self.assertTrue(sect["sect_member_utils_application_injected"])
        self.assertTrue(sect["sect_member_utils_no_legacy_manager"])
        self.assertTrue(sect["sect_member_utils_info_reads_feature_owned"])
        self.assertTrue(sect["sect_member_utils_join_count_feature_owned"])
        self.assertTrue(sect["sect_user_profile_repository_owned"])
        self.assertTrue(sect["sect_user_profile_facade_owned"])
        self.assertTrue(sect["sect_user_profile_helper_default_owned"])
        self.assertTrue(sect["sect_user_name_profile_repository_owned"])
        self.assertTrue(sect["sect_user_name_profile_facade_owned"])
        self.assertTrue(sect["sect_weekly_progress_profile_application_owned"])
        self.assertTrue(sect["sect_weekly_progress_manager_no_legacy_manager"])
        self.assertTrue(sect["activity_timestamp_application_owned"])
        self.assertTrue(sect["activity_timestamp_repository_owned"])
        self.assertTrue(sect["activity_timestamp_clock_injected"])
        self.assertTrue(sect["activity_timestamp_legacy_format_preserved"])
        self.assertTrue(sect["activity_timestamp_order_preserved"])
        self.assertTrue(sect["activity_timestamp_read_application_owned"])
        self.assertTrue(sect["activity_timestamp_read_repository_owned"])
        self.assertTrue(sect["activity_timestamp_legacy_timezone_safe"])
        natal = slices["natal_treasure"]
        self.assertTrue(natal["awaken_application_owned"])
        self.assertTrue(natal["legacy_awaken_disabled"])
        world_events = slices["world_events"]
        self.assertTrue(world_events["claim_application_owned"])
        self.assertTrue(world_events["attack_application_owned"])
        self.assertTrue(world_events["attack_legacy_settlement_disconnected"])
        self.assertTrue(world_events["legacy_attack_settlement_isolated"])
        self.assertTrue(world_events["attack_request_path_has_no_ddl"])
        self.assertTrue(world_events["attack_player_migration_registered"])
        self.assertTrue(world_events["attack_player_migration_routed"])
        self.assertTrue(world_events["lifecycle_application_owned"])
        self.assertTrue(world_events["lifecycle_default_has_no_legacy_service"])
        self.assertTrue(world_events["legacy_lifecycle_service_isolated"])
        self.assertTrue(world_events["lifecycle_request_path_has_no_ddl"])
        self.assertTrue(world_events["lifecycle_player_migration_registered"])
        self.assertTrue(world_events["lifecycle_player_migration_routed"])
        self.assertTrue(world_events["wave_refresh_application_owned"])
        self.assertTrue(world_events["wave_refresh_default_has_no_legacy_service"])
        self.assertTrue(world_events["legacy_wave_refresh_service_isolated"])
        self.assertTrue(world_events["wave_refresh_request_path_has_no_ddl"])
        self.assertTrue(world_events["wave_refresh_player_migration_registered"])
        self.assertTrue(world_events["wave_refresh_player_migration_routed"])
        self.assertTrue(world_events["spirit_vein_application_owned"])
        self.assertTrue(world_events["spirit_vein_default_has_no_legacy_service"])
        self.assertTrue(world_events["legacy_spirit_vein_service_isolated"])
        self.assertTrue(world_events["spirit_vein_request_path_has_no_ddl"])
        self.assertTrue(world_events["spirit_vein_player_migration_registered"])
        self.assertTrue(world_events["spirit_vein_player_migration_routed"])
        self.assertTrue(world_events["claim_repository_owned"])
        self.assertTrue(world_events["claim_request_path_has_no_ddl"])
        self.assertTrue(world_events["claim_game_migration_registered"])
        self.assertTrue(world_events["claim_game_migration_routed"])
        self.assertTrue(world_events["legacy_claim_service_isolated"])
        self.assertTrue(world_events["legacy_claim_disabled"])
        rift = slices["rift"]
        self.assertTrue(rift["entry_application_owned"])
        self.assertTrue(rift["legacy_entry_disabled"])
        self.assertTrue(rift["demon_token_application_owned"])
        self.assertTrue(rift["legacy_demon_token_disabled"])
        self.assertTrue(rift["demon_token_migrations_registered"])
        self.assertTrue(rift["speedup_default_repository_owned"])
        self.assertTrue(rift["speedup_migrations_registered"])
        self.assertTrue(rift["speedup_request_path_has_no_ddl"])
        self.assertTrue(rift["legacy_speedup_getter_disabled"])
        self.assertTrue(rift["generation_application_owned"])
        self.assertTrue(rift["legacy_generation_disabled"])
        self.assertTrue(rift["generation_migrations_registered"])
        self.assertTrue(rift["generation_request_path_has_no_ddl"])
        self.assertTrue(rift["termination_application_owned"])
        self.assertTrue(rift["legacy_termination_disabled"])
        self.assertTrue(rift["termination_migrations_registered"])
        self.assertTrue(rift["termination_request_path_has_no_ddl"])
        self.assertTrue(rift["key_event_default_repository_owned"])
        self.assertTrue(rift["legacy_key_event_disabled"])
        self.assertTrue(rift["key_event_migrations_registered"])
        self.assertTrue(rift["key_event_request_path_has_no_ddl"])
        self.assertTrue(rift["settlement_default_repository_owned"])
        self.assertTrue(rift["legacy_settlement_disabled"])
        self.assertTrue(rift["settlement_migrations_registered"])
        self.assertTrue(rift["settlement_request_path_has_no_ddl"])
        self.assertTrue(rift["entry_default_repository_owned"])
        self.assertTrue(rift["entry_migrations_registered"])
        self.assertTrue(rift["entry_request_path_has_no_ddl"])
        self.assertTrue(rift["entry_read_projection_repository_owned"])
        self.assertTrue(rift["entry_read_projection_has_no_ddl"])
        self.assertTrue(rift["legacy_entry_read_disabled"])
        self.assertTrue(rift["cooldown_read_projection_repository_owned"])
        self.assertTrue(rift["cooldown_read_request_path_has_no_ddl"])
        self.assertTrue(rift["legacy_cooldown_read_disabled"])
        self.assertTrue(rift["boss_battle_engine_provider_wired"])
        self.assertTrue(rift["boss_battle_buff_random_source_wired"])
        self.assertTrue(rift["boss_battle_status_writeback_isolated"])
        self.assertTrue(rift["boss_battle_skill_provider_read_only"])
        self.assertTrue(rift["boss_battle_item_provider_read_only"])
        self.assertTrue(rift["boss_battle_items_lazy"])
        back = slices["back"]
        self.assertTrue(back["daily_pill_usage_reset_application_owned"])
        self.assertTrue(back["daily_pill_usage_reset_atomic_no_request_ddl"])
        self.assertTrue(back["cultivation_item_application_owned"])
        self.assertTrue(back["legacy_cultivation_item_disabled"])
        self.assertTrue(back["skill_learning_application_owned"])
        self.assertTrue(back["legacy_skill_learning_disabled"])
        self.assertTrue(back["lottery_talisman_application_owned"])
        self.assertTrue(back["legacy_lottery_talisman_disabled"])
        self.assertTrue(back["stone_reward_application_owned"])
        self.assertTrue(back["legacy_stone_reward_disabled"])
        self.assertTrue(back["three_cultivation_pill_application_owned"])
        self.assertTrue(back["legacy_three_cultivation_pill_disabled"])
        self.assertTrue(back["breakthrough_rate_item_application_owned"])
        self.assertTrue(back["legacy_breakthrough_rate_item_disabled"])
        self.assertTrue(back["recovery_item_application_owned"])
        self.assertTrue(back["legacy_recovery_item_disabled"])
        self.assertTrue(back["permanent_atk_item_application_owned"])
        self.assertTrue(back["legacy_permanent_atk_item_disabled"])
        self.assertTrue(back["alchemy_application_owned"])
        self.assertTrue(back["legacy_alchemy_disabled"])
        self.assertTrue(back["unbind_application_owned"])
        self.assertTrue(back["legacy_unbind_disabled"])
        self.assertTrue(back["repair_application_owned"])
        self.assertTrue(back["legacy_repair_disabled"])
        partner_cultivation = slices["partner_cultivation"]
        self.assertTrue(partner_cultivation["application_owned"])
        self.assertTrue(partner_cultivation["repository_owned"])
        self.assertTrue(partner_cultivation["legacy_default_disabled"])
        self.assertTrue(partner_cultivation["usage_settled_atomically"])
        self.assertTrue(partner_cultivation["migration_owned"])
        self.assertTrue(partner_cultivation["request_path_has_no_ddl"])
        past_life = slices["past_life"]
        self.assertTrue(past_life["item_catalog_lazy"])
        self.assertTrue(past_life["reset_one_application_owned"])
        self.assertTrue(past_life["legacy_reset_one_disabled"])
        self.assertTrue(past_life["reset_all_application_owned"])
        self.assertTrue(past_life["legacy_reset_all_disabled"])
        dufang = slices["dufang"]
        self.assertTrue(dufang["share_application_owned"])
        self.assertTrue(dufang["legacy_share_disabled"])
        fusion = slices["fusion"]
        self.assertTrue(fusion["single_application_owned"])
        self.assertTrue(fusion["legacy_single_disabled"])
        self.assertTrue(fusion["batch_application_owned"])
        self.assertTrue(fusion["legacy_batch_disabled"])
        self.assertTrue(fusion["item_catalog_lazy"])
        self.assertTrue(fusion["legacy_service_factory_removed"])
        self.assertTrue(fusion["repository_transaction_owned"])
        self.assertTrue(fusion["request_path_has_no_ddl"])
        self.assertTrue(fusion["operation_schema_migration_owned"])
        self.assertTrue(fusion["legacy_import_identity_preserved"])
        title = slices["title"]
        self.assertTrue(title["equip_replay_application_owned"])
        self.assertTrue(title["legacy_equip_replay_disabled"])
        self.assertTrue(title["legacy_unequip_replay_disabled"])
        self.assertTrue(title["unlock_batch_application_owned"])
        self.assertTrue(title["legacy_unlock_batch_disabled"])
        self.assertTrue(title["title_state_read_application_owned"])
        self.assertTrue(title["title_state_read_legacy_disabled"])
        self.assertTrue(title["title_state_read_has_no_ddl"])
        self.assertTrue(title["mentor_title_grant_application_owned"])
        self.assertTrue(title["mentor_title_state_read_application_owned"])
        self.assertTrue(title["legacy_mentor_title_writer_disabled"])
        boss = slices["boss"]
        self.assertTrue(boss["reward_integral_application_owned"])
        self.assertTrue(boss["reward_integral_legacy_writer_disabled"])
        base = slices["base"]
        self.assertTrue(base["reward_service_legacy_connection_lazy"])
        self.assertTrue(base["reward_service_item_catalog_lazy"])
        self.assertTrue(base["rename_application_owned"])
        self.assertTrue(base["legacy_rename_disabled"])
        self.assertTrue(base["rename_service_isolated"])
        self.assertTrue(base["stone_contest_service_isolated"])
        self.assertTrue(base["stone_contest_default_application_owned"])
        self.assertTrue(base["stone_contest_web_route_application_owned"])
        self.assertTrue(base["stone_contest_request_path_has_no_ddl"])
        self.assertTrue(base["stone_contest_startup_migration_registered"])
        self.assertTrue(base["stone_theft_default_application_owned"])
        self.assertTrue(base["stone_theft_request_path_has_no_ddl"])
        self.assertTrue(base["stone_theft_startup_migration_registered"])
        self.assertTrue(base["stone_theft_migration_game_only"])
        self.assertTrue(base["stone_robbery_default_application_owned"])
        self.assertTrue(base["stone_robbery_request_path_has_no_ddl"])
        self.assertTrue(base["stone_robbery_startup_migrations_registered"])
        self.assertTrue(base["stone_robbery_migrations_routed_game_and_player"])
        self.assertTrue(base["stone_robbery_service_isolated"])
        self.assertTrue(base["root_reroll_default_application_owned"])
        self.assertTrue(base["root_reroll_repository_has_no_request_ddl"])
        self.assertTrue(base["root_reroll_startup_migration_registered"])
        self.assertTrue(base["root_reroll_migration_game_only"])
        self.assertTrue(base["xiangyuan_service_isolated"])
        self.assertTrue(base["breakthrough_service_isolated"])
        self.assertTrue(base["ordinary_tribulation_service_isolated"])
        self.assertTrue(base["destiny_tribulation_service_isolated"])
        self.assertTrue(base["heart_devil_tribulation_service_isolated"])
        self.assertTrue(base["pill_fusion_service_isolated"])
        self.assertTrue(base["tribulation_state_migration_service_isolated"])
        puppet = slices["puppet"]
        self.assertTrue(puppet["purchase_application_owned"])
        self.assertTrue(puppet["upgrade_application_owned"])
        self.assertTrue(puppet["harvest_application_owned"])
        self.assertTrue(puppet["legacy_harvest_disabled"])
        self.assertTrue(puppet["default_application_has_no_legacy_repository"])
        self.assertTrue(puppet["status_application_owned"])
        self.assertTrue(puppet["legacy_status_io_disabled"])
        self.assertTrue(puppet["scheduler_enabled_users_bounded"])
        self.assertTrue(puppet["status_schema_startup_migration_registered"])
        self.assertTrue(puppet["status_repository_has_no_request_ddl_and_uses_ledger"])
        self.assertTrue(puppet["status_replay_conflict_and_rollback_covered"])
        pet = slices["pet"]
        self.assertTrue(pet["active_switch_application_owned"])
        self.assertTrue(pet["skill_replace_application_owned"])
        self.assertTrue(pet["legacy_skill_replace_disabled"])
        self.assertTrue(pet["legacy_active_switch_disabled"])
        trade = slices["trade"]
        self.assertTrue(trade["xianshi_listing_application_owned"])
        self.assertTrue(trade["xianshi_auto_listing_application_owned"])
        self.assertTrue(trade["legacy_xianshi_auto_listing_disabled"])
        self.assertTrue(trade["xianshi_fast_listing_application_owned"])
        self.assertTrue(trade["legacy_xianshi_fast_listing_disabled"])
        self.assertTrue(trade["xianshi_system_listing_application_owned"])
        self.assertTrue(trade["legacy_xianshi_system_listing_disabled"])
        self.assertTrue(trade["xianshi_name_removal_application_owned"])
        self.assertTrue(trade["legacy_xianshi_name_removal_disabled"])
        self.assertTrue(trade["xianshi_admin_removal_application_owned"])
        self.assertTrue(trade["legacy_xianshi_admin_removal_disabled"])
        self.assertTrue(trade["xianshi_clear_application_owned"])
        self.assertTrue(trade["legacy_xianshi_clear_disabled"])
        self.assertTrue(trade["purchase_application_owned"])
        self.assertTrue(trade["purchase_compatibility_repository_direct"])
        self.assertTrue(trade["legacy_purchase_disabled"])
        self.assertTrue(trade["guishi_compatibility_repository_direct"])
        self.assertTrue(trade["guishi_legacy_service_isolated"])
        self.assertTrue(trade["guishi_legacy_getter_removed"])
        self.assertTrue(trade["guishi_deposit_application_owned"])
        self.assertTrue(trade["legacy_guishi_deposit_disabled"])
        self.assertTrue(trade["guishi_withdraw_application_owned"])
        self.assertTrue(trade["legacy_guishi_withdraw_disabled"])
        self.assertTrue(trade["guishi_qiugou_application_owned"])
        self.assertTrue(trade["legacy_guishi_qiugou_disabled"])
        self.assertTrue(trade["guishi_baitan_application_owned"])
        self.assertTrue(trade["legacy_guishi_baitan_disabled"])
        self.assertTrue(trade["guishi_cancel_qiugou_application_owned"])
        self.assertTrue(trade["legacy_guishi_cancel_qiugou_disabled"])
        self.assertTrue(trade["guishi_cancel_baitan_application_owned"])
        self.assertTrue(trade["legacy_guishi_cancel_baitan_disabled"])
        self.assertTrue(trade["guishi_matching_application_owned"])
        self.assertTrue(trade["legacy_guishi_matching_disabled"])
        self.assertTrue(trade["guishi_expired_cleanup_application_owned"])
        self.assertTrue(trade["legacy_guishi_expired_cleanup_disabled"])
        self.assertTrue(trade["guishi_take_application_owned"])
        self.assertTrue(trade["legacy_guishi_take_disabled"])
        auction = slices["auction"]
        self.assertTrue(auction["bid_application_owned"])
        self.assertTrue(auction["bid_effects_owned"])
        self.assertTrue(auction["bid_outbox_reconcile_owned"])
        self.assertTrue(auction["bid_started_operation_recoverable"])
        self.assertTrue(auction["queue_application_owned"])
        self.assertTrue(auction["queue_display_queries_application_owned"])
        self.assertTrue(auction["legacy_queue_disabled"])
        self.assertTrue(auction["session_start_application_owned"])
        self.assertTrue(auction["session_start_uses_settlement_application"])
        self.assertTrue(auction["settlement_application_owned"])
        self.assertTrue(auction["settlement_effects_owned"])
        self.assertTrue(auction["settlement_outbox_reconcile_owned"])
        self.assertTrue(auction["settlement_projection_ids_idempotent"])
        self.assertTrue(auction["settlement_started_operation_recoverable"])
        self.assertTrue(auction["settlement_compat_effects_disabled"])
        self.assertTrue(auction["legacy_settlement_disabled"])
        self.assertTrue(auction["trade_web_actions_application_owned"])
        self.assertTrue(auction["trade_web_finish_uses_settlement_ledger_directly"])
        self.assertTrue(auction["trade_web_session_routes_admin"])
        self.assertTrue(auction["trade_web_real_route_replay_and_effects_covered"])
        self.assertTrue(auction["legacy_trade_auction_session_isolated"])
        self.assertTrue(auction["legacy_trade_auction_session_feature_owned"])
        self.assertTrue(auction["legacy_settlement_adapter_feature_owned"])
        self.assertTrue(auction["display_queries_application_owned"])
        self.assertTrue(auction["display_query_repository_does_not_own_ddl"])
        self.assertTrue(auction["scheduler_query_application_owned"])
        boss = slices["boss"]
        self.assertTrue(boss["manual_spawn_application_owned"])
        self.assertTrue(boss["legacy_manual_spawn_disabled"])
        self.assertTrue(boss["manual_spawn_repository_owned"])
        self.assertTrue(boss["daily_limit_repository_owned"])
        self.assertTrue(boss["world_boss_request_path_has_no_ddl"])
        self.assertTrue(boss["world_boss_player_migration_registered"])
        self.assertTrue(boss["full_refresh_application_owned"])
        self.assertTrue(boss["full_refresh_repository_owned"])
        self.assertTrue(boss["full_refresh_migration_registered"])
        self.assertTrue(boss["full_refresh_request_path_has_no_ddl"])
        self.assertTrue(boss["full_refresh_replay_cas_and_rollback"])
        self.assertTrue(boss["full_refresh_legacy_service_not_default"])
        self.assertTrue(boss["battle_application_owned"])
        self.assertTrue(boss["legacy_battle_settlement_disabled"])
        buff = slices["buff"]
        self.assertTrue(buff["blessed_open_application_owned"])
        self.assertTrue(buff["legacy_blessed_open_disabled"])
        self.assertTrue(buff["blessed_rename_application_owned"])
        self.assertTrue(buff["legacy_blessed_rename_disabled"])
        self.assertTrue(buff["blessed_upgrade_application_owned"])
        self.assertTrue(buff["legacy_blessed_upgrade_disabled"])
        impart = slices["impart"]
        self.assertTrue(impart["love_sand_application_owned"])
        self.assertTrue(impart["card_compose_application_owned"])
        self.assertTrue(impart["card_disassemble_application_owned"])
        self.assertTrue(impart["prayer_stats_transaction_owned"])
        self.assertTrue(impart["prayer_request_path_has_no_ddl"])
        self.assertTrue(impart["prayer_schema_migrations_owned"])
        mixelixir = slices["mixelixir"]
        self.assertTrue(mixelixir["harvest_level_application_owned"])
        self.assertTrue(mixelixir["legacy_harvest_level_disabled"])
        self.assertTrue(mixelixir["daily_reset_application_owned"])
        self.assertTrue(mixelixir["daily_reset_atomic_and_no_request_ddl"])
        self.assertTrue(mixelixir["runtime_default_has_no_legacy_repository"])
        self.assertTrue(slices["dongfu"]["plant_application_owned"])
        self.assertTrue(slices["dongfu"]["harvest_application_owned"])
        self.assertTrue(slices["dongfu"]["harvest_snapshot_application_owned"])
        self.assertTrue(slices["dongfu"]["harvest_effects_outbox_atomic"])
        self.assertTrue(slices["dongfu"]["visit_reward_payload_is_stable_and_replay_preserves_gain"])
        self.assertTrue(slices["dongfu"]["infiltration_plan_freezes_branch_and_operation_id"])
        self.assertTrue(slices["dongfu"]["legacy_infiltration_receipts_replayed_before_checks"])
        self.assertTrue(slices["dongfu"]["static_map_and_visit_profile_reads_are_feature_owned"])
        self.assertTrue(slices["dongfu"]["fertilize_application_owned"])
        self.assertTrue(slices["dongfu"]["accelerate_application_owned"])
        self.assertTrue(slices["dongfu"]["patrol_application_owned"])
        self.assertTrue(slices["dongfu"]["inventory_facade_has_no_direct_mutator"])
        self.assertTrue(slices["dongfu"]["infiltrate_success_application_owned"])
        self.assertTrue(slices["dongfu"]["legacy_infiltrate_success_disabled"])
        self.assertTrue(slices["dongfu"]["infiltrate_failure_application_owned"])
        self.assertTrue(slices["dongfu"]["legacy_infiltrate_failure_disabled"])
        self.assertTrue(slices["dongfu"]["legacy_transactions_isolated"])
        self.assertTrue(slices["dongfu"]["legacy_transaction_compatibility_preserved"])
        self.assertTrue(slices["dongfu"]["operation_request_paths_have_no_ddl"])
        self.assertTrue(slices["dongfu"]["operation_schema_startup_migration_owned"])
        self.assertTrue(slices["impart_pk"]["training_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_training_replay_disabled"])
        self.assertTrue(slices["impart_pk"]["closing_enter_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_closing_enter_replay_disabled"])
        self.assertTrue(slices["impart_pk"]["closing_settlement_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_closing_settlement_replay_disabled"])
        self.assertTrue(slices["impart_pk"]["explore_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_explore_replay_disabled"])
        self.assertTrue(slices["impart_pk"]["battle_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_battle_replay_disabled"])
        self.assertTrue(slices["admin"]["item_destroy_application_owned"])
        self.assertTrue(slices["admin"]["rename_application_owned"])
        self.assertTrue(slices["admin"]["exp_adjust_application_owned"])
        self.assertTrue(slices["admin"]["level_change_application_owned"])
        self.assertTrue(slices["admin"]["legacy_realm_adaptation_application_owned"])
        self.assertTrue(slices["admin"]["legacy_realm_adaptation_repository_atomic"])
        self.assertTrue(slices["admin"]["legacy_realm_adaptation_request_path_has_no_ddl"])
        self.assertTrue(slices["admin"]["legacy_realm_adaptation_replay_and_rollback_covered"])
        self.assertTrue(slices["admin"]["novice_reset_application_owned"])
        self.assertTrue(slices["admin"]["novice_reset_repository_uses_existing_ledger"])
        self.assertTrue(slices["admin"]["novice_reset_request_path_has_no_ddl"])
        self.assertTrue(slices["admin"]["novice_reset_replay_and_rollback_covered"])
        self.assertTrue(slices["admin"]["root_change_application_owned"])
        self.assertTrue(slices["admin"]["impart_stone_application_owned"])
        self.assertTrue(slices["admin"]["accessory_application_owned"])
        self.assertTrue(slices["admin"]["player_status_batch_application_owned"])
        self.assertTrue(slices["admin"]["item_batch_application_owned"])
        self.assertTrue(slices["admin"]["accessory_batch_application_owned"])
        self.assertTrue(slices["admin"]["impart_stone_batch_application_owned"])
        self.assertTrue(slices["admin"]["impart_stone_batch_request_path_has_no_ddl"])
        self.assertTrue(slices["admin"]["impart_stone_batch_disk_preflight_and_bounded_roster"])
        self.assertTrue(slices["admin"]["impart_stone_batch_startup_migration_registered"])
        self.assertTrue(slices["admin"]["impart_stone_batch_migration_game_only"])
        self.assertTrue(slices["admin"]["blackhouse_application_owned"])
        self.assertTrue(slices["admin"]["player_status_application_owned"])
        self.assertTrue(slices["admin"]["stone_default_application_owned"])
        self.assertTrue(slices["admin"]["stone_legacy_repository_not_default_composed"])
        self.assertTrue(slices["admin"]["stone_request_path_has_no_ddl"])
        self.assertTrue(slices["admin"]["stone_replay_payload_and_audit_atomic"])
        self.assertTrue(slices["admin"]["stone_startup_migration_registered"])
        self.assertTrue(slices["admin"]["stone_started_operation_recoverable"])
        self.assertTrue(slices["admin"]["global_stone_batch_application_owned"])
        self.assertTrue(slices["admin"]["global_stone_batch_legacy_update_removed"])
        self.assertTrue(slices["admin"]["global_stone_batch_async_and_resumable"])
        self.assertTrue(slices["admin"]["global_stone_batch_duplicate_request_guarded"])
        self.assertTrue(slices["admin"]["global_stone_batch_request_path_has_no_ddl"])
        self.assertTrue(slices["admin"]["global_stone_batch_disk_preflight"])
        self.assertTrue(slices["admin"]["global_stone_batch_startup_migration_registered"])
        self.assertTrue(slices["admin"]["exp_request_path_has_no_ddl"])
        self.assertTrue(slices["admin"]["exp_startup_migration_registered"])
        self.assertTrue(slices["admin"]["item_destroy_request_path_has_no_ddl"])
        self.assertTrue(slices["admin"]["item_destroy_startup_migration_registered"])
        self.assertTrue(slices["admin"]["item_destroy_missing_schema_reported"])
        self.assertTrue(slices["admin"]["item_destroy_migration_game_only"])
        self.assertTrue(slices["admin"]["item_grant_request_path_has_no_ddl"])
        self.assertTrue(slices["admin"]["item_grant_startup_migration_registered"])
        self.assertTrue(slices["admin"]["item_grant_schema_missing_reported"])
        self.assertTrue(slices["admin"]["item_grant_migration_game_only"])
        self.assertTrue(slices["impart"]["prayer_application_owned"])
        self.assertTrue(slices["rift"]["speedup_application_owned"])
        self.assertTrue(slices["rift"]["settlement_application_owned"])
        self.assertTrue(slices["boss"]["daily_limit_application_owned"])
        self.assertTrue(slices["boss"]["punishment_application_owned"])
        self.assertTrue(slices["boss"]["item_catalog_lazy"])
        self.assertTrue(slices["buff"]["stone_training_application_owned"])
        self.assertTrue(slices["buff"]["player_experience_normalization_owned"])
        self.assertTrue(slices["buff"]["training_lifecycle_application_owned"])
        self.assertTrue(slices["buff"]["training_lifecycle_request_path_has_no_ddl"])
        self.assertTrue(slices["buff"]["training_lifecycle_startup_migrations_registered"])
        self.assertTrue(slices["buff"]["training_lifecycle_stats_and_weekly_task_owned"])
        self.assertTrue(slices["buff"]["closing_settlement_application_owned"])
        self.assertTrue(slices["buff"]["pvp_application_owned"])
        self.assertTrue(slices["buff"]["partner_token_application_owned"])
        self.assertTrue(slices["buff"]["legacy_partner_token_disabled"])
        self.assertTrue(slices["back"]["equipment_unequip_application_owned"])
        self.assertTrue(slices["back"]["equipment_equip_application_owned"])
        self.assertTrue(slices["back"]["pet_egg_application_owned"])
        self.assertTrue(slices["back"]["package_application_owned"])
        self.assertTrue(slices["back"]["accessory_package_application_owned"])
        self.assertTrue(slices["natal_treasure"]["effect_upgrade_application_owned"])
        self.assertTrue(slices["world_events"]["attack_application_owned"])
        self.assertTrue(slices["sect"]["daily_maintenance_application_owned"])
        self.assertTrue(slices["rift"]["key_event_application_owned"])
        self.assertTrue(slices["dongfu"]["array_upgrade_application_owned"])
        self.assertTrue(slices["dongfu"]["expansion_slots_persisted_with_assets"])
        self.assertTrue(slices["dongfu"]["expansion_handler_has_no_legacy_writeback"])
        self.assertTrue(slices["dongfu"]["harvest_snapshot_application_owned"])
        self.assertTrue(slices["dongfu"]["harvest_snapshot_handler_has_no_legacy_writeback"])
        self.assertTrue(slices["dongfu"]["status_read_application_owned"])
        self.assertTrue(slices["dongfu"]["status_read_has_no_legacy_writeback"])
        self.assertTrue(slices["dongfu"]["infiltration_eligibility_has_no_legacy_writeback"])
        self.assertTrue(slices["dongfu"]["status_display_has_no_legacy_writeback"])
        self.assertTrue(slices["dongfu"]["status_schema_startup_migration_owned"])
        self.assertTrue(slices["base"]["refund_stamina_application_owned"])
        self.assertTrue(slices["tower"]["stamina_refund_application_owned"])
        self.assertTrue(slices["player_state"]["battle_vital_write_application_owned"])
        self.assertTrue(slices["player_state"]["battle_vital_legacy_writer_disabled"])
        self.assertTrue(slices["player_state"]["battle_vital_repository_is_bounded_and_no_ddl"])
        self.assertTrue(slices["player_state"]["battle_vital_schema_failure_is_observable"])

    def test_progress_report_tracks_daily_sign_reset_ownership(self) -> None:
        sign_in = _slice_status()["sign_in"]
        self.assertTrue(sign_in["daily_reset_application_owned"])
        self.assertTrue(sign_in["daily_reset_atomic_no_request_ddl"])
        self.assertTrue(sign_in["daily_reset_replay_rollback_and_missing_schema_covered"])
        self.assertTrue(sign_in["daily_reset_historical_date_ambiguity_documented"])


if __name__ == "__main__":
    unittest.main()
