from __future__ import annotations

import unittest

from scripts.check_full_refactor_progress import _slice_status


class RefactorProgressTests(unittest.TestCase):
    def test_progress_report_tracks_arena_cutovers_and_active_blockers(self) -> None:
        slices = _slice_status()
        arena = slices["arena"]
        self.assertTrue(arena["state_application_owned"])
        self.assertTrue(arena["legacy_state_owner_disabled"])
        self.assertTrue(arena["weekly_rank_application_owned"])
        self.assertTrue(arena["legacy_scheduler_disabled"])
        self.assertTrue(arena["daily_reward_application_owned"])
        self.assertTrue(arena["legacy_daily_reward_disabled"])
        self.assertFalse(slices["sign_in"]["lottery_compatibility_fallback"])
        self.assertTrue(slices["sign_in"]["effects_outbox_reconcile_owned"])
        tower = slices["tower"]
        self.assertTrue(tower["state_application_owned"])
        self.assertTrue(tower["legacy_state_owner_disabled"])
        training = slices["training"]
        self.assertTrue(training["state_application_owned"])
        self.assertTrue(training["legacy_state_owner_disabled"])
        work = slices["work"]
        self.assertTrue(work["daily_refresh_application_owned"])
        self.assertTrue(work["legacy_daily_refresh_disabled"])
        self.assertTrue(work["item_accelerate_application_owned"])
        self.assertTrue(work["legacy_item_accelerate_disabled"])
        self.assertTrue(work["capture_application_owned"])
        self.assertTrue(work["legacy_item_capture_disabled"])
        self.assertTrue(work["capture_json_projection_only"])
        self.assertTrue(work["item_use_migrations_registered"])
        activity = slices["activity_reward"]
        self.assertTrue(activity["claim_all_application_owned"])
        self.assertTrue(activity["legacy_claim_all_disabled"])
        dungeon_team = slices["dungeon_team"]
        self.assertTrue(dungeon_team["create_invite_application_owned"])
        self.assertTrue(dungeon_team["legacy_create_invite_disabled"])
        bank = slices["bank"]
        self.assertTrue(bank["deposit_application_owned"])
        self.assertTrue(bank["withdrawal_application_owned"])
        self.assertTrue(bank["upgrade_application_owned"])
        self.assertTrue(bank["interest_application_owned"])
        self.assertTrue(bank["legacy_deposit_disabled"])
        self.assertTrue(bank["legacy_withdrawal_disabled"])
        self.assertTrue(bank["legacy_upgrade_disabled"])
        self.assertTrue(bank["legacy_interest_disabled"])
        map_slice = slices["map"]
        self.assertTrue(map_slice["interactive_application_owned"])
        self.assertTrue(map_slice["resource_application_owned"])
        self.assertTrue(map_slice["legacy_interactive_disabled"])
        self.assertTrue(map_slice["legacy_resource_disabled"])
        sect = slices["sect"]
        self.assertTrue(sect["membership_application_owned"])
        self.assertTrue(sect["economy_application_owned"])
        self.assertTrue(sect["legacy_membership_disabled"])
        natal = slices["natal_treasure"]
        self.assertTrue(natal["awaken_application_owned"])
        self.assertTrue(natal["legacy_awaken_disabled"])
        world_events = slices["world_events"]
        self.assertTrue(world_events["claim_application_owned"])
        self.assertTrue(world_events["legacy_claim_disabled"])
        rift = slices["rift"]
        self.assertTrue(rift["entry_application_owned"])
        self.assertTrue(rift["legacy_entry_disabled"])
        self.assertTrue(rift["demon_token_application_owned"])
        self.assertTrue(rift["legacy_demon_token_disabled"])
        self.assertTrue(rift["demon_token_migrations_registered"])
        self.assertTrue(rift["speedup_default_repository_owned"])
        self.assertTrue(rift["speedup_migrations_registered"])
        self.assertTrue(rift["speedup_request_path_has_no_ddl"])
        self.assertTrue(rift["legacy_speedup_getter_disabled"])
        self.assertTrue(rift["generation_application_owned"])
        self.assertTrue(rift["legacy_generation_disabled"])
        self.assertTrue(rift["generation_migrations_registered"])
        self.assertTrue(rift["generation_request_path_has_no_ddl"])
        self.assertTrue(rift["termination_application_owned"])
        self.assertTrue(rift["legacy_termination_disabled"])
        self.assertTrue(rift["termination_migrations_registered"])
        self.assertTrue(rift["termination_request_path_has_no_ddl"])
        self.assertTrue(rift["key_event_default_repository_owned"])
        self.assertTrue(rift["legacy_key_event_disabled"])
        self.assertTrue(rift["key_event_migrations_registered"])
        self.assertTrue(rift["key_event_request_path_has_no_ddl"])
        self.assertTrue(rift["settlement_default_repository_owned"])
        self.assertTrue(rift["legacy_settlement_disabled"])
        self.assertTrue(rift["settlement_migrations_registered"])
        self.assertTrue(rift["settlement_request_path_has_no_ddl"])
        self.assertTrue(rift["entry_default_repository_owned"])
        self.assertTrue(rift["entry_migrations_registered"])
        self.assertTrue(rift["entry_request_path_has_no_ddl"])
        self.assertTrue(rift["entry_read_projection_repository_owned"])
        self.assertTrue(rift["entry_read_projection_has_no_ddl"])
        self.assertTrue(rift["legacy_entry_read_disabled"])
        self.assertTrue(rift["cooldown_read_projection_repository_owned"])
        self.assertTrue(rift["cooldown_read_request_path_has_no_ddl"])
        self.assertTrue(rift["legacy_cooldown_read_disabled"])
        self.assertTrue(rift["boss_battle_engine_provider_wired"])
        self.assertTrue(rift["boss_battle_buff_random_source_wired"])
        self.assertTrue(rift["boss_battle_status_writeback_isolated"])
        self.assertTrue(rift["boss_battle_skill_provider_read_only"])
        self.assertTrue(rift["boss_battle_item_provider_read_only"])
        self.assertTrue(rift["boss_battle_items_lazy"])
        back = slices["back"]
        self.assertTrue(back["cultivation_item_application_owned"])
        self.assertTrue(back["legacy_cultivation_item_disabled"])
        self.assertTrue(back["skill_learning_application_owned"])
        self.assertTrue(back["legacy_skill_learning_disabled"])
        self.assertTrue(back["lottery_talisman_application_owned"])
        self.assertTrue(back["legacy_lottery_talisman_disabled"])
        self.assertTrue(back["stone_reward_application_owned"])
        self.assertTrue(back["legacy_stone_reward_disabled"])
        self.assertTrue(back["three_cultivation_pill_application_owned"])
        self.assertTrue(back["legacy_three_cultivation_pill_disabled"])
        self.assertTrue(back["breakthrough_rate_item_application_owned"])
        self.assertTrue(back["legacy_breakthrough_rate_item_disabled"])
        self.assertTrue(back["recovery_item_application_owned"])
        self.assertTrue(back["legacy_recovery_item_disabled"])
        self.assertTrue(back["permanent_atk_item_application_owned"])
        self.assertTrue(back["legacy_permanent_atk_item_disabled"])
        self.assertTrue(back["alchemy_application_owned"])
        self.assertTrue(back["legacy_alchemy_disabled"])
        self.assertTrue(back["unbind_application_owned"])
        self.assertTrue(back["legacy_unbind_disabled"])
        self.assertTrue(back["repair_application_owned"])
        self.assertTrue(back["legacy_repair_disabled"])
        partner_cultivation = slices["partner_cultivation"]
        self.assertTrue(partner_cultivation["application_owned"])
        self.assertTrue(partner_cultivation["repository_owned"])
        self.assertTrue(partner_cultivation["legacy_default_disabled"])
        self.assertTrue(partner_cultivation["usage_settled_atomically"])
        self.assertTrue(partner_cultivation["migration_owned"])
        self.assertTrue(partner_cultivation["request_path_has_no_ddl"])
        past_life = slices["past_life"]
        self.assertTrue(past_life["reset_one_application_owned"])
        self.assertTrue(past_life["legacy_reset_one_disabled"])
        self.assertTrue(past_life["reset_all_application_owned"])
        self.assertTrue(past_life["legacy_reset_all_disabled"])
        dufang = slices["dufang"]
        self.assertTrue(dufang["share_application_owned"])
        self.assertTrue(dufang["legacy_share_disabled"])
        fusion = slices["fusion"]
        self.assertTrue(fusion["single_application_owned"])
        self.assertTrue(fusion["legacy_single_disabled"])
        self.assertTrue(fusion["batch_application_owned"])
        self.assertTrue(fusion["legacy_batch_disabled"])
        title = slices["title"]
        self.assertTrue(title["equip_replay_application_owned"])
        self.assertTrue(title["legacy_equip_replay_disabled"])
        self.assertTrue(title["legacy_unequip_replay_disabled"])
        self.assertTrue(title["unlock_batch_application_owned"])
        self.assertTrue(title["legacy_unlock_batch_disabled"])
        base = slices["base"]
        self.assertTrue(base["rename_application_owned"])
        self.assertTrue(base["legacy_rename_disabled"])
        self.assertTrue(base["rename_service_isolated"])
        self.assertTrue(base["stone_contest_service_isolated"])
        self.assertTrue(base["stone_robbery_service_isolated"])
        puppet = slices["puppet"]
        self.assertTrue(puppet["harvest_application_owned"])
        self.assertTrue(puppet["legacy_harvest_disabled"])
        pet = slices["pet"]
        self.assertTrue(pet["active_switch_application_owned"])
        self.assertTrue(pet["skill_replace_application_owned"])
        self.assertTrue(pet["legacy_skill_replace_disabled"])
        self.assertTrue(pet["legacy_active_switch_disabled"])
        trade = slices["trade"]
        self.assertTrue(trade["xianshi_listing_application_owned"])
        self.assertTrue(trade["xianshi_auto_listing_application_owned"])
        self.assertTrue(trade["legacy_xianshi_auto_listing_disabled"])
        self.assertTrue(trade["xianshi_fast_listing_application_owned"])
        self.assertTrue(trade["legacy_xianshi_fast_listing_disabled"])
        self.assertTrue(trade["xianshi_system_listing_application_owned"])
        self.assertTrue(trade["legacy_xianshi_system_listing_disabled"])
        self.assertTrue(trade["xianshi_name_removal_application_owned"])
        self.assertTrue(trade["legacy_xianshi_name_removal_disabled"])
        self.assertTrue(trade["xianshi_admin_removal_application_owned"])
        self.assertTrue(trade["legacy_xianshi_admin_removal_disabled"])
        self.assertTrue(trade["xianshi_clear_application_owned"])
        self.assertTrue(trade["legacy_xianshi_clear_disabled"])
        self.assertTrue(trade["purchase_application_owned"])
        self.assertTrue(trade["purchase_compatibility_repository_direct"])
        self.assertTrue(trade["legacy_purchase_disabled"])
        self.assertTrue(trade["guishi_compatibility_repository_direct"])
        self.assertTrue(trade["guishi_legacy_service_isolated"])
        self.assertTrue(trade["guishi_legacy_getter_removed"])
        self.assertTrue(trade["guishi_deposit_application_owned"])
        self.assertTrue(trade["legacy_guishi_deposit_disabled"])
        self.assertTrue(trade["guishi_withdraw_application_owned"])
        self.assertTrue(trade["legacy_guishi_withdraw_disabled"])
        self.assertTrue(trade["guishi_qiugou_application_owned"])
        self.assertTrue(trade["legacy_guishi_qiugou_disabled"])
        self.assertTrue(trade["guishi_baitan_application_owned"])
        self.assertTrue(trade["legacy_guishi_baitan_disabled"])
        self.assertTrue(trade["guishi_cancel_qiugou_application_owned"])
        self.assertTrue(trade["legacy_guishi_cancel_qiugou_disabled"])
        self.assertTrue(trade["guishi_cancel_baitan_application_owned"])
        self.assertTrue(trade["legacy_guishi_cancel_baitan_disabled"])
        self.assertTrue(trade["guishi_matching_application_owned"])
        self.assertTrue(trade["legacy_guishi_matching_disabled"])
        self.assertTrue(trade["guishi_expired_cleanup_application_owned"])
        self.assertTrue(trade["legacy_guishi_expired_cleanup_disabled"])
        self.assertTrue(trade["guishi_take_application_owned"])
        self.assertTrue(trade["legacy_guishi_take_disabled"])
        auction = slices["auction"]
        self.assertTrue(auction["bid_application_owned"])
        self.assertTrue(auction["bid_effects_owned"])
        self.assertTrue(auction["bid_outbox_reconcile_owned"])
        self.assertTrue(auction["bid_started_operation_recoverable"])
        self.assertTrue(auction["queue_application_owned"])
        self.assertTrue(auction["queue_display_queries_application_owned"])
        self.assertTrue(auction["legacy_queue_disabled"])
        self.assertTrue(auction["session_start_application_owned"])
        self.assertTrue(auction["session_start_uses_settlement_application"])
        self.assertTrue(auction["settlement_application_owned"])
        self.assertTrue(auction["settlement_effects_owned"])
        self.assertTrue(auction["settlement_outbox_reconcile_owned"])
        self.assertTrue(auction["settlement_projection_ids_idempotent"])
        self.assertTrue(auction["settlement_started_operation_recoverable"])
        self.assertTrue(auction["settlement_compat_effects_disabled"])
        self.assertTrue(auction["legacy_settlement_disabled"])
        self.assertTrue(auction["trade_web_actions_application_owned"])
        self.assertTrue(auction["trade_web_finish_uses_settlement_ledger_directly"])
        self.assertTrue(auction["trade_web_session_routes_admin"])
        self.assertTrue(auction["trade_web_real_route_replay_and_effects_covered"])
        self.assertTrue(auction["legacy_trade_auction_session_isolated"])
        self.assertTrue(auction["legacy_trade_auction_session_feature_owned"])
        self.assertTrue(auction["legacy_settlement_adapter_feature_owned"])
        self.assertTrue(auction["display_queries_application_owned"])
        self.assertTrue(auction["display_query_repository_does_not_own_ddl"])
        self.assertTrue(auction["scheduler_query_application_owned"])
        boss = slices["boss"]
        self.assertTrue(boss["manual_spawn_application_owned"])
        self.assertTrue(boss["legacy_manual_spawn_disabled"])
        buff = slices["buff"]
        self.assertTrue(buff["blessed_open_application_owned"])
        self.assertTrue(buff["legacy_blessed_open_disabled"])
        self.assertTrue(buff["blessed_rename_application_owned"])
        self.assertTrue(buff["legacy_blessed_rename_disabled"])
        self.assertTrue(buff["blessed_upgrade_application_owned"])
        self.assertTrue(buff["legacy_blessed_upgrade_disabled"])
        impart = slices["impart"]
        self.assertTrue(impart["love_sand_application_owned"])
        self.assertTrue(impart["card_compose_application_owned"])
        self.assertTrue(impart["card_disassemble_application_owned"])
        self.assertTrue(impart["prayer_stats_transaction_owned"])
        self.assertTrue(impart["prayer_request_path_has_no_ddl"])
        self.assertTrue(impart["prayer_schema_migrations_owned"])
        mixelixir = slices["mixelixir"]
        self.assertTrue(mixelixir["harvest_level_application_owned"])
        self.assertTrue(mixelixir["legacy_harvest_level_disabled"])
        self.assertTrue(slices["dongfu"]["plant_application_owned"])
        self.assertTrue(slices["dongfu"]["harvest_application_owned"])
        self.assertTrue(slices["dongfu"]["fertilize_application_owned"])
        self.assertTrue(slices["dongfu"]["accelerate_application_owned"])
        self.assertTrue(slices["dongfu"]["patrol_application_owned"])
        self.assertTrue(slices["dongfu"]["infiltrate_success_application_owned"])
        self.assertTrue(slices["dongfu"]["legacy_infiltrate_success_disabled"])
        self.assertTrue(slices["dongfu"]["infiltrate_failure_application_owned"])
        self.assertTrue(slices["dongfu"]["legacy_infiltrate_failure_disabled"])
        self.assertTrue(slices["impart_pk"]["training_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_training_replay_disabled"])
        self.assertTrue(slices["impart_pk"]["closing_enter_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_closing_enter_replay_disabled"])
        self.assertTrue(slices["impart_pk"]["closing_settlement_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_closing_settlement_replay_disabled"])
        self.assertTrue(slices["impart_pk"]["explore_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_explore_replay_disabled"])
        self.assertTrue(slices["impart_pk"]["battle_replay_application_owned"])
        self.assertTrue(slices["impart_pk"]["legacy_battle_replay_disabled"])
        self.assertTrue(slices["admin"]["item_destroy_application_owned"])
        self.assertTrue(slices["admin"]["exp_adjust_application_owned"])
        self.assertTrue(slices["admin"]["level_change_application_owned"])
        self.assertTrue(slices["admin"]["root_change_application_owned"])
        self.assertTrue(slices["admin"]["impart_stone_application_owned"])
        self.assertTrue(slices["admin"]["accessory_application_owned"])
        self.assertTrue(slices["admin"]["player_status_batch_application_owned"])
        self.assertTrue(slices["admin"]["item_batch_application_owned"])
        self.assertTrue(slices["admin"]["accessory_batch_application_owned"])
        self.assertTrue(slices["admin"]["impart_stone_batch_application_owned"])
        self.assertTrue(slices["admin"]["blackhouse_application_owned"])
        self.assertTrue(slices["admin"]["player_status_application_owned"])
        self.assertTrue(slices["impart"]["prayer_application_owned"])
        self.assertTrue(slices["rift"]["speedup_application_owned"])
        self.assertTrue(slices["rift"]["settlement_application_owned"])
        self.assertTrue(slices["boss"]["daily_limit_application_owned"])
        self.assertTrue(slices["boss"]["punishment_application_owned"])
        self.assertTrue(slices["buff"]["stone_training_application_owned"])
        self.assertTrue(slices["buff"]["training_lifecycle_application_owned"])
        self.assertTrue(slices["buff"]["closing_settlement_application_owned"])
        self.assertTrue(slices["buff"]["pvp_application_owned"])
        self.assertTrue(slices["buff"]["partner_token_application_owned"])
        self.assertTrue(slices["buff"]["legacy_partner_token_disabled"])
        self.assertTrue(slices["back"]["equipment_unequip_application_owned"])
        self.assertTrue(slices["back"]["equipment_equip_application_owned"])
        self.assertTrue(slices["back"]["pet_egg_application_owned"])
        self.assertTrue(slices["back"]["package_application_owned"])
        self.assertTrue(slices["back"]["accessory_package_application_owned"])
        self.assertTrue(slices["natal_treasure"]["effect_upgrade_application_owned"])
        self.assertTrue(slices["world_events"]["attack_application_owned"])
        self.assertTrue(slices["sect"]["daily_maintenance_application_owned"])
        self.assertTrue(slices["rift"]["key_event_application_owned"])
        self.assertTrue(slices["dongfu"]["array_upgrade_application_owned"])
if __name__ == "__main__":
    unittest.main()
