"""Compatibility imports for historical pet transaction services."""

from ...compatibility.legacy_pet_transactions import (
    PetActiveSwitchResult,
    PetActiveSwitchService,
    PetFeedResult,
    PetFeedService,
    PetFusionBreakthroughResult,
    PetFusionBreakthroughService,
    PetHatchResult,
    PetHatchService,
    PetReleaseResult,
    PetReleaseService,
    PetSkillRerollResult,
    PetSkillRerollService,
    PetSkillReplaceResult,
    PetSkillReplaceService,
    PetTravelClaimResult,
    PetTravelClaimService,
    PetTravelStartResult,
    PetTravelStartService,
)

__all__ = [
    "PetTravelClaimResult",
    "PetTravelClaimService",
    "PetFeedResult",
    "PetFeedService",
    "PetSkillReplaceResult",
    "PetSkillReplaceService",
    "PetTravelStartResult",
    "PetTravelStartService",
    "PetHatchResult",
    "PetHatchService",
    "PetReleaseResult",
    "PetReleaseService",
    "PetFusionBreakthroughResult",
    "PetFusionBreakthroughService",
    "PetSkillRerollResult",
    "PetSkillRerollService",
    "PetActiveSwitchResult",
    "PetActiveSwitchService",
]
