from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Mapping

from ..package_reward.domain import PackageReward, normalize_rewards


@dataclass(frozen=True)
class AccessoryReward:
    """A stable accessory instance generated by the command adapter."""

    uid: str
    item_id: int | None = None
    name: str = ""
    part: str = ""
    set_type: str = ""
    quality: int = 0
    affixes: tuple[Any, ...] = ()
    locked_affixes: tuple[Any, ...] = ()
    wash_count: int = 0

    @classmethod
    def from_value(cls, value: Mapping[str, Any] | "AccessoryReward") -> "AccessoryReward":
        if isinstance(value, cls):
            return value
        return cls(
            uid=str(value.get("uid", "")).strip(),
            item_id=None if value.get("item_id") is None else int(value["item_id"]),
            name=str(value.get("name", "")),
            part=str(value.get("part", "")),
            set_type=str(value.get("set_type", "")),
            quality=int(value.get("quality", 0)),
            affixes=tuple(value.get("affixes", ()) or ()),
            locked_affixes=tuple(value.get("locked_affixes", ()) or ()),
            wash_count=int(value.get("wash_count", 0)),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "uid": self.uid,
            "item_id": self.item_id,
            "name": self.name,
            "part": self.part,
            "set_type": self.set_type,
            "quality": self.quality,
            "affixes": list(self.affixes),
            "locked_affixes": list(self.locked_affixes),
            "wash_count": self.wash_count,
        }

    def validate(self) -> None:
        if not self.uid:
            raise ValueError("accessory uid must not be empty")
        if self.quality < 0 or self.wash_count < 0:
            raise ValueError("accessory numeric fields must not be negative")


def normalize_accessories(values: Iterable[Mapping[str, Any] | AccessoryReward]) -> tuple[AccessoryReward, ...]:
    items = tuple(AccessoryReward.from_value(value) for value in values)
    if not items:
        raise ValueError("accessories must not be empty")
    for item in items:
        item.validate()
    if len({item.uid for item in items}) != len(items):
        raise ValueError("accessory uid must be unique")
    return items


__all__ = ["AccessoryReward", "PackageReward", "normalize_accessories", "normalize_rewards"]
