"""Manifest for routes owned by the runtime adapters themselves."""

from .registry import ConfigSpec, FeatureManifest, RouteSpec


FEATURE = FeatureManifest(
    key="runtime_web",
    title="运行时管理接口",
    owner="platform",
    config=(
        ConfigSpec("web_enabled", "bool", default=False, reloadable=True, description="是否启用新 Web 适配器"),
        ConfigSpec("web_host", "str", default="127.0.0.1", reloadable=True, description="Web 监听地址"),
        ConfigSpec("web_port", "int", default=5888, reloadable=True, description="Web 监听端口"),
        ConfigSpec("web_secret_key", "str", default=None, secret=True, description="Web session 密钥"),
        ConfigSpec("web_admin_ids", "list", default=(), description="允许登录管理面板的管理员 ID JSON 列表"),
        ConfigSpec("web_allowed_hosts", "list", default=(), reloadable=True, description="Web Host 白名单；为空时仅允许本机 Host"),
    ),
    routes=(
        RouteSpec("/", permission="public"),
        RouteSpec("/login", methods=("GET", "POST"), permission="public"),
        RouteSpec("/logout", permission="public"),
        RouteSpec("/favicon.ico", permission="public"),
        RouteSpec("/robots.txt", permission="public"),
        RouteSpec("/static/<path:filename>", permission="public"),
        RouteSpec("/health/live", permission="public"),
        RouteSpec("/health/ready", permission="public"),
        RouteSpec("/api/v1/registry", permission="public"),
        RouteSpec("/api/v1/csrf", permission="public"),
        RouteSpec("/api/v1/dashboard", permission="public"),
        RouteSpec("/api/v1/config", permission="admin"),
        RouteSpec("/api/v1/config", methods=("POST",), permission="admin"),
        RouteSpec("/api/v1/database", permission="admin"),
        RouteSpec("/api/v1/database/<key>/tables", permission="admin"),
        RouteSpec("/api/v1/reconcile", permission="admin"),
        RouteSpec("/api/v1/reconcile", methods=("POST",), permission="admin"),
        RouteSpec("/api/v1/scheduler", permission="admin"),
        RouteSpec("/api/v1/scheduler/<job_id>/run", methods=("POST",), permission="admin"),
        RouteSpec("/api/v1/backups", permission="admin"),
        RouteSpec("/api/v1/backups", methods=("POST",), permission="admin"),
        RouteSpec("/api/v1/backups/restore", methods=("POST",), permission="admin"),
        RouteSpec("/api/v1/activity", permission="admin"),
        RouteSpec("/api/v1/messages", permission="admin"),
        RouteSpec("/api/v1/logs", permission="admin"),
        RouteSpec("/messages", permission="admin"),
        RouteSpec("/config", permission="admin"),
        RouteSpec("/database", permission="admin"),
        RouteSpec("/scheduler", permission="admin"),
        RouteSpec("/backups", permission="admin"),
        RouteSpec("/activity", permission="admin"),
        RouteSpec("/pages/config", permission="admin"),
        RouteSpec("/pages/database", permission="admin"),
        RouteSpec("/pages/scheduler", permission="admin"),
        RouteSpec("/pages/backups", permission="admin"),
        RouteSpec("/pages/activity", permission="admin"),
        RouteSpec("/pages/logs", permission="admin"),
        RouteSpec("/pages/economy_logs", permission="admin"),
        RouteSpec("/pages/commands", permission="admin"),
        RouteSpec("/pages/command_registry", permission="admin"),
        RouteSpec("/pages/reward_center", permission="admin"),
        RouteSpec("/pages/update", permission="admin"),
        RouteSpec("/logs", permission="admin"),
        RouteSpec("/economy_logs", permission="admin"),
        RouteSpec("/commands", permission="admin"),
        RouteSpec("/command_registry", permission="admin"),
        RouteSpec("/reward-center", permission="admin"),
        RouteSpec("/update", permission="admin"),
    ),
    test_tag="runtime_web",
)


__all__ = ["FEATURE"]
