from __future__ import annotations

MAX_ACCOUNT_LIST_FILE_BYTES = 1024 * 1024
MAX_ACCOUNT_LIST_ROWS = 48
MAX_ACCOUNT_ID_CHARS = 24
MAX_ACCOUNT_BASE_URL_CHARS = 192
MAX_ACCOUNT_LABEL_CHARS = 64
MAX_CHECKIN_SECRET_CHARS = 4096
MAX_CHECKIN_BASE_URL_CHARS = 512
MAX_CHECKIN_SELECTOR_CHARS = 64
MAX_CHECKIN_HISTORY_BYTES = 64 * 1024
MAX_CHECKIN_HISTORY_ROWS = 3
MAX_CHECKIN_HISTORY_SUMMARY_CHARS = 500
MAX_INFO_TARGETS = 8

MAX_NEWAPI_LEGACY_FILES = 4096
MAX_NEWAPI_LEGACY_TOTAL_BYTES = 64 * 1024 * 1024

__all__ = [
    "MAX_ACCOUNT_BASE_URL_CHARS",
    "MAX_ACCOUNT_ID_CHARS",
    "MAX_ACCOUNT_LABEL_CHARS",
    "MAX_ACCOUNT_LIST_FILE_BYTES",
    "MAX_ACCOUNT_LIST_ROWS",
    "MAX_CHECKIN_BASE_URL_CHARS",
    "MAX_CHECKIN_HISTORY_BYTES",
    "MAX_CHECKIN_HISTORY_ROWS",
    "MAX_CHECKIN_HISTORY_SUMMARY_CHARS",
    "MAX_CHECKIN_SECRET_CHARS",
    "MAX_CHECKIN_SELECTOR_CHARS",
    "MAX_INFO_TARGETS",
    "MAX_NEWAPI_LEGACY_FILES",
    "MAX_NEWAPI_LEGACY_TOTAL_BYTES",
]
