
name: Compress 和 Release on Push

on:
  push:
    branches:
      - main  # 您可以指定需要触发的分支

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate tag name
      id: tag
      run: |
        # 获取最新的commit hash
        COMMIT_HASH=$(git rev-parse --short HEAD)
        # 设置tag名，例如v1，v2，v3...
        TAG_NAME="v$(date +%s)"
        echo "Tag name is $TAG_NAME"
        echo "::set-output name=tag::$TAG_NAME"

    - name: Compress project
      run: |
        tar -czvf project.tar.gz ./

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: Release ${{ steps.tag.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./project.tar.gz
        asset_name: project.tar.gz
        asset_content_type: application/gzip
